#Definition Namespace für alle Ressourcen
apiVersion: v1
kind: Namespace
metadata:
  name: JSVAR_NAMESPACE
---  
apiVersion: batch/v1
kind: Job
metadata:
  name: jdatabaseauth
  namespace: JSVAR_NAMESPACE
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: jdatabaseauth
        image: JSVAR_DOCKERIMAGE
        args:
        - /bin/bash
        - -c
        - /opt/gcSession.sh JSVAR_BA_DBNAME JSVAR_BA_DBUSER JSVAR_BA_DBPSWD
      restartPolicy: Never
